# Generated by Django 5.1.2 on 2025-04-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodlife', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='id',
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_id',
            field=models.AutoField(default=' ', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
